/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediinfosystem;


import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatPropertiesLaf;
import com.formdev.flatlaf.IntelliJTheme;
import controllers.loginController;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import view.appointmentAddGUI;
import view.complainAddGUI;
import view.homeAdminGUI;
import view.postAddGUI;
import view.refferenceAddViewGUI;
import view.userAddGUI;
import view.userViewGUI;
import view.visitorsAddGUI;



public class mainMenu extends javax.swing.JFrame {

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    int mousePx;
    int mousePy;
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        min_max_close = new javax.swing.JPanel();
        minmize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        close_btn_img = new javax.swing.JLabel();
        maximize = new javax.swing.JPanel();
        max_btn_img = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        menuSection = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        menu_show = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("HelvLight", 0, 24)); // NOI18N
        setUndecorated(true);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setForeground(new java.awt.Color(60, 63, 65));
        header.setPreferredSize(new java.awt.Dimension(800, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                headerMouseReleased(evt);
            }
        });
        header.setLayout(new java.awt.BorderLayout());

        min_max_close.setBackground(new java.awt.Color(51, 51, 51));
        min_max_close.setPreferredSize(new java.awt.Dimension(350, 30));
        min_max_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minmize.setBackground(new java.awt.Color(51, 51, 51));
        minmize.setPreferredSize(new java.awt.Dimension(100, 30));
        minmize.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(122, 134, 140));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/min_button.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        minmize.add(jLabel1, java.awt.BorderLayout.CENTER);

        min_max_close.add(minmize, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 80, -1));

        close.setBackground(new java.awt.Color(51, 51, 51));
        close.setPreferredSize(new java.awt.Dimension(70, 30));
        close.setLayout(new java.awt.BorderLayout());

        close_btn_img.setBackground(new java.awt.Color(122, 134, 140));
        close_btn_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_btn_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_button.png"))); // NOI18N
        close_btn_img.setToolTipText("close");
        close_btn_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btn_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btn_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btn_imgMouseExited(evt);
            }
        });
        close.add(close_btn_img, java.awt.BorderLayout.CENTER);

        min_max_close.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 100, -1));

        maximize.setBackground(new java.awt.Color(51, 51, 51));
        maximize.setPreferredSize(new java.awt.Dimension(100, 30));
        maximize.setLayout(new java.awt.BorderLayout());

        max_btn_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max_btn_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/max_button.png"))); // NOI18N
        max_btn_img.setToolTipText("maximize");
        max_btn_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_btn_imgMouseClicked(evt);
            }
        });
        maximize.add(max_btn_img, java.awt.BorderLayout.LINE_END);

        min_max_close.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 0, 150, -1));

        header.add(min_max_close, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medical Information System");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        header.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        left.setBackground(new java.awt.Color(231, 233, 235));
        left.setMaximumSize(new java.awt.Dimension(1000, 1320));
        left.setMinimumSize(new java.awt.Dimension(500, 660));
        left.setPreferredSize(new java.awt.Dimension(500, 670));
        left.setLayout(new java.awt.BorderLayout());

        menuSection.setBackground(new java.awt.Color(51, 51, 51));
        menuSection.setPreferredSize(new java.awt.Dimension(50, 670));
        menuSection.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(224, 49, 83));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        menuSection.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(224, 49, 83));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        menuSection.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        menuSection.add(jPanel3, java.awt.BorderLayout.LINE_END);

        left.add(menuSection, java.awt.BorderLayout.LINE_START);

        menu_show.setBackground(new java.awt.Color(255, 255, 255));
        menu_show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 49, 83), 10));
        menu_show.setMaximumSize(new java.awt.Dimension(1000, 1320));
        menu_show.setMinimumSize(new java.awt.Dimension(500, 660));
        menu_show.setPreferredSize(new java.awt.Dimension(600, 660));

        loginButton.setBackground(new java.awt.Color(224, 49, 83));
        loginButton.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        userName.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        userName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 49, 83), 2));
        userName.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("User Name");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Password");

        userPass.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        userPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 49, 83), 2));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login_pic.png"))); // NOI18N

        warningLabel.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(224, 49, 83));

        javax.swing.GroupLayout menu_showLayout = new javax.swing.GroupLayout(menu_show);
        menu_show.setLayout(menu_showLayout);
        menu_showLayout.setHorizontalGroup(
            menu_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_showLayout.createSequentialGroup()
                .addGroup(menu_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_showLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(menu_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menu_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(userPass, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(menu_showLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel5)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        menu_showLayout.setVerticalGroup(
            menu_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_showLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        left.add(menu_show, java.awt.BorderLayout.CENTER);

        getContentPane().add(left, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(51, 51, 51));
        content.setMaximumSize(new java.awt.Dimension(800, 800));
        content.setMinimumSize(new java.awt.Dimension(400, 600));
        content.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(224, 49, 83));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        content.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(224, 49, 83));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        content.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new java.awt.BorderLayout());
        content.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    private void close_btn_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btn_imgMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_btn_imgMouseClicked

    private void close_btn_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btn_imgMouseEntered
        
    }//GEN-LAST:event_close_btn_imgMouseEntered

    private void close_btn_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btn_imgMouseExited
        
    }//GEN-LAST:event_close_btn_imgMouseExited

    private void max_btn_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btn_imgMouseClicked
        if(this.getExtendedState()!=mainMenu.MAXIMIZED_BOTH){
        this.setExtendedState(MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(NORMAL);
        }
    }//GEN-LAST:event_max_btn_imgMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    this.setExtendedState(JFrame.ICONIFIED);    }//GEN-LAST:event_jLabel1MouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        
        
        if(!userName.getText().equals("") && !userPass.getPassword().equals("")){
            
            String userName=this.userName.getText();
            
            String userPass=new String(this.userPass.getPassword());
                                   
            String dbUserName="admin";
            String dbPass="123";
            
            loginController loginObj=new loginController(userName,userPass,dbUserName,dbPass);
            if(loginObj.loginChecker()){
                new homeAdminGUI().setVisible(true);
                this.setVisible(false);
            
            }else{
                
                warningLabel.setText("Login Details Are Wrong");
                
            }
            
        }else{
        
                warningLabel.setText("Enter Username & Password");
        
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int xCordinate=evt.getXOnScreen();
        int yCordinate=evt.getYOnScreen();
        changecolor(jPanel5,new Color(12,16,45));
        changecolor(min_max_close,new Color(12,16,45));
        changecolor(close,new Color(12,16,45));
        changecolor(minmize,new Color(12,16,45));
        changecolor(maximize,new Color(12,16,45));


        this.setLocation(xCordinate-mousePx,yCordinate-mousePy);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        
        mousePx=evt.getX();
        mousePy=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseReleased
        changecolor(jPanel5,new Color(51,51,51));
        changecolor(min_max_close,new Color(51,51,51));
        changecolor(close,new Color(51,51,51));
        changecolor(minmize,new Color(51,51,51));
        changecolor(maximize,new Color(51,51,51));

        
    }//GEN-LAST:event_headerMouseReleased

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        
        try {
            UIManager.setLookAndFeel( new FlatLightLaf());
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }
        //new refferenceAddViewGUI().setVisible(true);
        //new userViewGUI().setVisible(true);
        //new userAddGUI().setVisible(true);
        new homeAdminGUI().setVisible(true);
        //new complainAddGUI().setVisible(true);
        //new postAddGUI().setVisible(true);
        //new visitorsAddGUI().setVisible(true);
        //new appointmentAddGUI().setVisible(true);
        
        //BasicLookAndFeel darcula = new DarculaLaf();
        //UIManager.setLookAndFeel(darcula);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel close;
    private javax.swing.JLabel close_btn_img;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel left;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel max_btn_img;
    private javax.swing.JPanel maximize;
    private javax.swing.JPanel menuSection;
    private javax.swing.JPanel menu_show;
    private javax.swing.JPanel min_max_close;
    private javax.swing.JPanel minmize;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPass;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
